### ISSUE TITLE
Create config file for CLI

### ISSUE THREAD

**Issue by SlnPons** [massalabs/DeWeb#101]
**Context**
Create a config file to store needed info to be able to choose the parameters that can changed (node, chunk size, ...)

**How to**

- [x] Check if there is an official way to handle config files using Commander
- [x] Check if more options can be put into the config file (address? no need for wallet #102 )
- [x] Implement the config handling based on the found solution

**Tech info**
```yaml
# The URL to the node to connect to
node_url: "https://buildnet.massa.net/api/v2"
# The max number of slots to wait for an operations to be included into a block
expiry: 9
```
